### ISSUE TITLE
First trial of Stroop only works after refreshing page

### ISSUE THREAD

**Issue by psychological** [ErwinHaasnoot/QRTEngine#42]
Hi there,

I'm running a study that contains two Stroop tasks (i.e., a practice one and then a full 96 trial one). To give you some further context, participants are randomly assigned to two different versions of these two Stroop tasks: one which contains some incongruent stimuli and another condition which contains only congruent stimuli. There are other additional questionnaires before and after the Stroop tasks and there are instructions between the two Stroop tasks.

The practice task is working fine now after I changed the page transition from fade to none (I'm using the Minimal theme as recommended in the Stroop tutorial), but at the beginning of the second stroop task, the plus sign shows up, disappears, but then the first stimulus doesn't appear. If I refresh the page, it appears and the rest of the trials work perfectly. I'd like it so that one does not have to refresh the page for the second study to run smoothly.

Here is the link to the .qsf file:
https://www.dropbox.com/s/rgnko07dgamw0nv/Personality_Perception_Emotions_and_Decision_Making.qsf?dl=0

Thanks for your help,
Colin

**Comment by psychological** [comment]
Hi again,

The same issue remains when I use v15_jfe_fix. I'm still not sure what the source of the problem is or how I can solve it. Any help would be very much appreciated. The link in my previous post contains the updated .qsf file of the study after incorporating v15_jfe_fix. 

Colin

**Comment by ErwinHaasnoot** [comment]
Hi Colin,

Thanks, I will check it out. Didn't get to it the other day.

**Comment by psychological** [comment]
Hi Erwin,

Just following up and wondering if you have had the chance to look this over.

Colin

**Comment by ErwinHaasnoot** [comment]
Hi Colin,

Sorry about the delay. I have checked it out, the survey seems to work fine for me on Chrome & Firefox. What browser are you testing it in?

I have imported your QSF and hte preview can be found here: https://eu.qualtrics.com/jfe/preview/SV_0W16sTIVVwQ7Qbz

Is it working for you? (I switched the order of the blocks, the one you reported to be broken is shown first)

**Comment by psychological** [comment]
Hi Erwin,

Thanks for looking into this for me. I'm testing it in Chrome as well. I'm
getting a blank screen at the end of the first Stroop task now though (?).

Colin

**Comment by psychological** [comment]
I think it might be a transition issue as things work once I press refresh.
The only problems appear to be occurring at the start or end of the Stroop
task.

**Comment by psychological** [comment]
Hi Erwin,

Sorry to bug you again. Do you mind taking one last look at what may be going on here? Thanks in advance!

Colin

**Comment by evapoort** [comment]
Hi both,

I've recently been having the same issue with my lexical decision task. It's divided into 8 blocks with breaks in between and the first block of the task runs fine, but after the first break, it freezes on the fixation cross and I have to re-load the page to get the experiment to continue running. Could someone of the QRTE team possibly look into this, please?

Some additional info:
Each block of the lexical decision task actually consists of two blocks, a short block of 6 fillers and a longer block of 42 experimental stimuli. Sometimes the experiment freezes when it gets to the first filler, but other times it gets through the fillers okay and then freezes when it gets to the first experimental stimulus. When I reload the page, it gets through the rest of the block okay, but then freezes again after the next break.

Finally, after the main lexical decision task, I have two shorter lexical decision tasks, the first of which usually still has problems, but the second (and final) task is completely fine.

Thanks in advance!

Eva

**Comment by ErwinHaasnoot** [comment]
Hi all,

Sorry about the long period of silence..

I'm thinking this issue is related to ticket #43 by @LiaStern2015. I have pushed a fix for her issue, would you mind testing the survey with the newest v15_jfe_fix?

Best,

Erwin

**Comment by ErwinHaasnoot** [comment]
This would be the version oft he QRTEngine you'd need to use:

https://raw.githubusercontent.com/ErwinHaasnoot/QRTEngine/v15/lib/QRTEngine.js

**Comment by evapoort** [comment]
Hi Erwin,

Thanks for taking a look at this! I'm afraid, though, that the new version linked above doesn't fix the issue for me. The practice and first block of my task still work fine, but after the first break (and all subsequent breaks), the fillers (usually) show up fine but the experiment freezes for the first experimental trial of that block. When I refresh the page, I get a message saying that my session expired, though when I click OK, the experiment does continue running. The second task runs smoothly again, as does the third. In case you want a look at the experiment, I've uploaded a .qsf file: https://www.dropbox.com/s/yx9bnypzsz3m13g/Experiment_EvaPoort.qsf?dl=0.

Thanks,
Eva

**Comment by ErwinHaasnoot** [comment]
Hi Eva,

Thanks for checking the fix. I'll try and see if anything else is wrong
with the .qsf you uploaded. I think the problem might be related to the one
I fixed, so hopefully it won't take too long to figure out.

**Comment by evapoort** [comment]
Thanks! By the way, it says on some screens to press the S button to continue, but I have since disabled that, so the only way to continue to the next screen is to click on the ">>" button. I thought using the waitForKey function was related to this issue, so tried commenting it out, which doesn't seem to have fixed anything, but I haven't uncommented it yet...

**Comment by evapoort** [comment]
Hi Erwin,

I know you're probably busy, but I just wanted to check... Have you had any time to look at my survey?

Thanks,
Eva
